#!/usr/bin/env node
// Standalone per-role inbox viewer. Generated by zudui; no zudui runtime deps.
// Polls the broker every POLL_MS ms and rewrites the screen in place (no scroll).
"use strict";

const fs = require("fs");
const path = require("path");

const POLL_MS = 2000;
const MAX_ROWS = 20;

const credentialsPath = path.join(__dirname, "credentials.json");
let creds;
try {
  creds = JSON.parse(fs.readFileSync(credentialsPath, "utf8"));
} catch (e) {
  process.stderr.write(`✖ cannot read ${credentialsPath}: ${e.message}\n`);
  process.exit(2);
}

const { agent_id, address, api_key, broker_url } = creds;
for (const [k, v] of Object.entries({ agent_id, address, api_key, broker_url })) {
  if (typeof v !== "string" || !v) {
    process.stderr.write(`✖ credentials.json missing '${k}'\n`);
    process.exit(2);
  }
}

const ANSI = {
  clear: "\u001b[2J\u001b[H",
  dim: "\u001b[2m",
  reset: "\u001b[0m",
  bold: "\u001b[1m",
  cyan: "\u001b[36m",
  yellow: "\u001b[33m",
  green: "\u001b[32m",
  red: "\u001b[31m",
};

function truncate(s, n) {
  if (typeof s !== "string") return "";
  return s.length <= n ? s : s.slice(0, n - 1) + "…";
}

function fmtTime(iso) {
  if (typeof iso !== "string") return "";
  return iso.slice(0, 19).replace("T", " ");
}

async function fetchInbox() {
  const url =
    `${broker_url}/messages/inbox/${encodeURIComponent(address)}` +
    `?agent_id=${encodeURIComponent(agent_id)}`;
  const resp = await fetch(url, { headers: { "X-API-Key": api_key } });
  if (!resp.ok) {
    const body = await resp.text().catch(() => "");
    throw new Error(`HTTP ${resp.status}${body ? `: ${body.slice(0, 200)}` : ""}`);
  }
  const data = await resp.json();
  if (!Array.isArray(data)) throw new Error("inbox response was not a JSON array");
  return data;
}

function render(msgs, err) {
  process.stdout.write(ANSI.clear);
  const now = fmtTime(new Date().toISOString());
  const header =
    `${ANSI.bold}${ANSI.cyan}zudui inbox${ANSI.reset} ` +
    `· ${address} · ${ANSI.dim}${now}${ANSI.reset}`;
  process.stdout.write(header + "\n");
  process.stdout.write("─".repeat(80) + "\n");

  if (err) {
    process.stdout.write(`${ANSI.red}error:${ANSI.reset} ${err.message}\n`);
    process.stdout.write(`${ANSI.dim}retrying in ${POLL_MS / 1000}s · Ctrl+C to exit${ANSI.reset}\n`);
    return;
  }

  const unread = msgs.filter((m) => m && m.is_read === false);
  process.stdout.write(
    `${ANSI.bold}${unread.length}${ANSI.reset} unread / ${msgs.length} total ` +
      `${ANSI.dim}(showing up to ${MAX_ROWS})${ANSI.reset}\n\n`,
  );

  for (const m of unread.slice(0, MAX_ROWS)) {
    const from = truncate(m.from_agent || "(unknown)", 40);
    const subj = truncate(m.subject || "", 60);
    const time = fmtTime(m.created_at);
    const action = (m.action || "send").padEnd(7);
    process.stdout.write(
      `${ANSI.yellow}●${ANSI.reset} ${ANSI.dim}[${time}]${ANSI.reset} ` +
        `${ANSI.cyan}${action}${ANSI.reset} ${from}\n`,
    );
    process.stdout.write(`    ${subj}\n`);
  }
  if (unread.length === 0) {
    process.stdout.write(`${ANSI.dim}(nothing new — broker quiet)${ANSI.reset}\n`);
  }
  process.stdout.write(`\n${ANSI.dim}Ctrl+C to exit · refresh every ${POLL_MS / 1000}s${ANSI.reset}\n`);
}

let timer = null;
let running = false;

async function tick() {
  if (running) return; // skip overlap if previous tick still in flight
  running = true;
  try {
    const msgs = await fetchInbox();
    render(msgs);
  } catch (e) {
    render(null, e);
  } finally {
    running = false;
  }
}

process.on("SIGINT", () => {
  if (timer) clearInterval(timer);
  process.stdout.write("\n");
  process.exit(0);
});

tick();
timer = setInterval(tick, POLL_MS);
