"use strict";

const fs = require("fs");
const path = require("path");

// Launcher commands keyed by framework. The script wraps `cd <role>/ && exec <cmd>`
// so each role launches the user's chosen agent in its own workdir.
const FRAMEWORK_CMD = {
  claude: { cmd: "claude", label: "Claude Code" },
  infiniti: { cmd: "infiniti", label: "Infiniti-Agent" },
};

function shScript(roleDir, frameworkCmd) {
  return [
    "#!/bin/sh",
    "# Auto-generated by zudui. Launches the role's agent in its workdir.",
    'set -e',
    'DIR="$(cd "$(dirname "$0")" && pwd)"',
    `cd "$DIR/${roleDir}"`,
    `exec ${frameworkCmd}`,
    "",
  ].join("\n");
}

function cmdScript(roleDir, frameworkCmd) {
  return [
    "@echo off",
    "REM Auto-generated by zudui. Launches the role's agent in its workdir.",
    `cd /d "%~dp0${roleDir}"`,
    `${frameworkCmd}`,
    "",
  ].join("\r\n");
}

function writeStartScripts(rootDir, role, framework) {
  const spec = FRAMEWORK_CMD[framework];
  if (!spec) {
    throw new Error(`unknown framework '${framework}' for role ${role}`);
  }
  const shPath = path.join(rootDir, `start-${role}.sh`);
  const cmdPath = path.join(rootDir, `start-${role}.cmd`);
  fs.writeFileSync(shPath, shScript(role, spec.cmd), { mode: 0o755 });
  fs.writeFileSync(cmdPath, cmdScript(role, spec.cmd));
  return { shPath, cmdPath, label: spec.label };
}

module.exports = { FRAMEWORK_CMD, writeStartScripts };
